---
- name: Télécharger Spark
  get_url:
    url: "{{ spark_download_url }}"
    dest: "/tmp/spark-{{ spark_version }}.tgz"
    timeout: 300

- name: Créer répertoire Spark
  file:
    path: "{{ spark_install_dir }}"
    state: directory
    owner: spark
    group: spark
    mode: '0755'

- name: Extraire Spark
  unarchive:
    src: "/tmp/spark-{{ spark_version }}.tgz"
    dest: "{{ spark_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: spark
    group: spark

- name: Configurer spark-env.sh
  template:
    src: spark-env.sh.j2
    dest: "{{ spark_home }}/conf/spark-env.sh"
    owner: spark
    group: spark
    mode: '0755'

- name: Ajouter SPARK_HOME au profile
  lineinfile:
    path: /etc/profile.d/spark.sh
    line: "{{ item }}"
    create: yes
    mode: '0644'
  loop:
    - "export SPARK_HOME={{ spark_home }}"
    - "export PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin"

- name: Créer répertoires
  file:
    path: "{{ item }}"
    state: directory
    owner: spark
    group: spark
    mode: '0755'
  loop:
    - "{{ spark_home }}/logs"
    - "{{ spark_home }}/work"

- name: Créer service systemd Worker
  template:
    src: spark-worker.service.j2
    dest: /etc/systemd/system/spark-worker.service
    mode: '0644'

- name: Recharger systemd
  systemd:
    daemon_reload: yes

- name: Démarrer Spark Worker
  systemd:
    name: spark-worker
    state: started
    enabled: yes