---
# Variables par défaut pour HDFS
hadoop_version: "3.3.6"
hadoop_download_url: "https://archive.apache.org/dist/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
hadoop_install_dir: "/opt/hadoop"
hadoop_home: "{{ hadoop_install_dir }}"
hadoop_conf_dir: "{{ hadoop_home }}/etc/hadoop"

# Utilisateur et groupe
hadoop_user: "hadoop"
hadoop_group: "hadoop"

# Répertoires HDFS
hdfs_namenode_dir: "/data/hadoop/hdfs/namenode"
hdfs_datanode_dir: "/data/hadoop/hdfs/datanode"
hdfs_tmp_dir: "/data/hadoop/tmp"

# Configuration HDFS
hdfs_replication_factor: 2
hdfs_block_size: "128m"

# Ports
namenode_port: 9000
namenode_http_port: 9870
datanode_port: 9866
datanode_http_port: 9864